/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Gigabyte
 */
public class ForgotPass extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPass
     */
    
    public Frame frame;
    
    public ForgotPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameFld = new javax.swing.JTextField();
        secQ1Fld = new javax.swing.JPasswordField();
        secQ2Fld = new javax.swing.JPasswordField();
        changePassBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SECURITY Svcs");
        jLabel1.setToolTipText("");

        usernameFld.setBackground(new java.awt.Color(240, 240, 240));
        usernameFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameFld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "USERNAME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        usernameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameFldKeyReleased(evt);
            }
        });

        secQ1Fld.setBackground(new java.awt.Color(240, 240, 240));
        secQ1Fld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        secQ1Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secQ1Fld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "WHAT IS YOUR OLDEST SIBLING'S NAME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        secQ1Fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secQ1FldKeyReleased(evt);
            }
        });

        secQ2Fld.setBackground(new java.awt.Color(240, 240, 240));
        secQ2Fld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        secQ2Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secQ2Fld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "WHAT WAS YOUR CHILDHOOD NICKNAME?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        changePassBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changePassBtn.setText("CHANGE PASSWORD");
        changePassBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setText("<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(secQ2Fld)
                    .addComponent(secQ1Fld)
                    .addComponent(usernameFld)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(changePassBtn)))
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backBtn)))
                .addGap(40, 40, 40)
                .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(secQ1Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(secQ2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        secQ1Fld.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFldKeyReleased
        
    }//GEN-LAST:event_usernameFldKeyReleased

    private void secQ1FldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secQ1FldKeyReleased
     
    }//GEN-LAST:event_secQ1FldKeyReleased

    private void changePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassBtnActionPerformed
        User user = frame.main.sqlite.getUser(usernameFld.getText().toLowerCase());
        String secQ1 = frame.main.hashPassword(String.valueOf(secQ1Fld.getPassword()));
        String secQ2 = frame.main.hashPassword(String.valueOf(secQ2Fld.getPassword()));
        
        if(user == null){
            JOptionPane.showMessageDialog(frame,
                    "Username does not exist.",
                     "Forgot Password Error",
                 JOptionPane.ERROR_MESSAGE);
        }
        else if(!secQ1.equals(user.getSecQ1()) || !secQ2.equals(user.getSecQ2())){
            JOptionPane.showMessageDialog(frame,
                    "Incorrect answer/s in security question/s.",
                     "Forgot Password Error",
                 JOptionPane.ERROR_MESSAGE);
        }
        else{
            frame.changePassPnl.usernameFld.setText(user.getUsername());
            usernameFld.setText("");
            secQ1Fld.setText("");
            secQ2Fld.setText("");
            frame.changePassNav();
        }
    }//GEN-LAST:event_changePassBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        usernameFld.setText("");
        secQ1Fld.setText("");
        secQ2Fld.setText("");
        frame.loginNav();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changePassBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField secQ1Fld;
    private javax.swing.JPasswordField secQ2Fld;
    private javax.swing.JTextField usernameFld;
    // End of variables declaration//GEN-END:variables
}
